"""db/seed.py — Seed default plans and add-ons on first startup."""
from __future__ import annotations

from decimal import Decimal
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
import structlog

from models.subscription import AddOn, Plan

log = structlog.get_logger(__name__)

PLANS = [
    {
        "slug": "starter",
        "display_name": "Starter",
        "tagline": "Everything you need to start collecting feedback",
        "description": "Perfect for small NGOs, community-based organisations, and local government units.",
        "monthly_price_usd": Decimal("49.00"),
        "annual_price_usd":  Decimal("39.00"),
        "trial_days": 14,
        "sort_order": 1,
        # Limits
        "max_team_members": 5,
        "max_projects": 3,
        "max_submissions_per_month": 500,
        "max_sms_per_month": 200,
        "max_api_calls_per_month": 0,
        "max_storage_gb": 5,
        "max_qr_per_month": 0,
        "max_staff_profiles": 0,
        # Features
        "has_sms_channel": False,
        "has_whatsapp_channel": False,
        "has_phone_call_ai": False,
        "has_ai_conversation": False,
        "has_ai_insights": False,
        "has_voice_transcription": False,
        "has_push_notifications": False,
        "has_whatsapp_notif": False,
        "has_advanced_analytics": False,
        "has_custom_reports": False,
        "has_spark_streaming": False,
        "has_ml_predictor": False,
        "has_qr_generation": False,
        "has_product_verification": False,
        "has_ai_counterfeit": False,
        "has_field_agents": False,
        "has_staff_verification": False,
        "has_queue_management": False,
        "has_stakeholder_engagement": False,
        "has_translation": False,
        "has_api_access": False,
        "has_webhooks": False,
        "has_oauth2": False,
        "has_widget_embed": False,
        "has_payment_processing": False,
        "has_employee_feedback": False,
        "has_pap_registry": False,
        "has_committee_mgmt": False,
        "has_bulk_import": False,
        "has_sso": False,
        "has_2fa": False,
        "has_white_label": False,
        "has_dedicated_support": False,
        "has_custom_sla": False,
        "uptime_sla": "99.5%",
    },
    {
        "slug": "professional",
        "display_name": "Professional",
        "tagline": "AI-powered GRM for growing organisations",
        "description": "Ideal for hospitals, universities, utilities, and mid-size banks.",
        "monthly_price_usd": Decimal("149.00"),
        "annual_price_usd":  Decimal("119.00"),
        "trial_days": 14,
        "sort_order": 2,
        "max_team_members": 25,
        "max_projects": 15,
        "max_submissions_per_month": 5000,
        "max_sms_per_month": 2000,
        "max_api_calls_per_month": 10000,
        "max_storage_gb": 25,
        "max_qr_per_month": 500,
        "max_staff_profiles": 100,
        "has_sms_channel": True,
        "has_whatsapp_channel": True,
        "has_phone_call_ai": False,
        "has_ai_conversation": True,
        "has_ai_insights": False,
        "has_voice_transcription": True,
        "has_push_notifications": True,
        "has_whatsapp_notif": True,
        "has_advanced_analytics": True,
        "has_custom_reports": False,
        "has_spark_streaming": False,
        "has_ml_predictor": False,
        "has_qr_generation": True,
        "has_product_verification": True,
        "has_ai_counterfeit": False,
        "has_field_agents": False,
        "has_staff_verification": True,
        "has_queue_management": False,
        "has_stakeholder_engagement": False,
        "has_translation": False,
        "has_api_access": True,
        "has_webhooks": False,
        "has_oauth2": True,
        "has_widget_embed": True,
        "has_payment_processing": False,
        "has_employee_feedback": True,
        "has_pap_registry": True,
        "has_committee_mgmt": False,
        "has_bulk_import": False,
        "has_sso": False,
        "has_2fa": True,
        "has_white_label": False,
        "has_dedicated_support": False,
        "has_custom_sla": False,
        "uptime_sla": "99.9%",
    },
    {
        "slug": "business",
        "display_name": "Business",
        "tagline": "Full-stack GRM for enterprises and governments",
        "description": "Built for commercial banks, government ministries, large hospitals, and international NGOs.",
        "monthly_price_usd": Decimal("399.00"),
        "annual_price_usd":  Decimal("319.00"),
        "trial_days": 14,
        "sort_order": 3,
        "max_team_members": 100,
        "max_projects": -1,
        "max_submissions_per_month": -1,
        "max_sms_per_month": 10000,
        "max_api_calls_per_month": 100000,
        "max_storage_gb": 100,
        "max_qr_per_month": -1,
        "max_staff_profiles": -1,
        "has_sms_channel": True,
        "has_whatsapp_channel": True,
        "has_phone_call_ai": True,
        "has_ai_conversation": True,
        "has_ai_insights": True,
        "has_voice_transcription": True,
        "has_push_notifications": True,
        "has_whatsapp_notif": True,
        "has_advanced_analytics": True,
        "has_custom_reports": True,
        "has_spark_streaming": True,
        "has_ml_predictor": True,
        "has_qr_generation": True,
        "has_product_verification": True,
        "has_ai_counterfeit": True,
        "has_field_agents": True,
        "has_staff_verification": True,
        "has_queue_management": True,
        "has_stakeholder_engagement": True,
        "has_translation": True,
        "has_api_access": True,
        "has_webhooks": True,
        "has_oauth2": True,
        "has_widget_embed": True,
        "has_payment_processing": True,
        "has_employee_feedback": True,
        "has_pap_registry": True,
        "has_committee_mgmt": True,
        "has_bulk_import": True,
        "has_sso": False,
        "has_2fa": True,
        "has_white_label": False,
        "has_dedicated_support": True,
        "has_custom_sla": False,
        "uptime_sla": "99.95%",
    },
    {
        "slug": "enterprise",
        "display_name": "Enterprise",
        "tagline": "Unlimited power. Dedicated support. Custom everything.",
        "description": "For World Bank, UN agencies, governments, multinationals, and donor programmes.",
        "monthly_price_usd": Decimal("0"),
        "annual_price_usd":  Decimal("0"),
        "trial_days": 30,
        "sort_order": 4,
        "is_custom": True,
        "max_team_members": -1,
        "max_projects": -1,
        "max_submissions_per_month": -1,
        "max_sms_per_month": -1,
        "max_api_calls_per_month": -1,
        "max_storage_gb": -1,
        "max_qr_per_month": -1,
        "max_staff_profiles": -1,
        "has_sms_channel": True,
        "has_whatsapp_channel": True,
        "has_phone_call_ai": True,
        "has_ai_conversation": True,
        "has_ai_insights": True,
        "has_voice_transcription": True,
        "has_push_notifications": True,
        "has_whatsapp_notif": True,
        "has_advanced_analytics": True,
        "has_custom_reports": True,
        "has_spark_streaming": True,
        "has_ml_predictor": True,
        "has_qr_generation": True,
        "has_product_verification": True,
        "has_ai_counterfeit": True,
        "has_field_agents": True,
        "has_staff_verification": True,
        "has_queue_management": True,
        "has_stakeholder_engagement": True,
        "has_translation": True,
        "has_api_access": True,
        "has_webhooks": True,
        "has_oauth2": True,
        "has_widget_embed": True,
        "has_payment_processing": True,
        "has_employee_feedback": True,
        "has_pap_registry": True,
        "has_committee_mgmt": True,
        "has_bulk_import": True,
        "has_sso": True,
        "has_2fa": True,
        "has_white_label": True,
        "has_dedicated_support": True,
        "has_custom_sla": True,
        "uptime_sla": "99.99%",
    },
]

ADDONS = [
    {"slug": "extra-sms-1k",     "name": "Extra SMS Bundle (1,000)",    "type": "extra_sms",       "price_usd": Decimal("10.00"), "unit": "SMS",      "unit_quantity": 1000},
    {"slug": "extra-users-5",    "name": "Extra Team Members (5)",      "type": "extra_users",     "price_usd": Decimal("25.00"), "unit": "users",    "unit_quantity": 5},
    {"slug": "extra-storage-10g","name": "Extra Storage (10 GB)",       "type": "extra_storage",   "price_usd": Decimal("5.00"),  "unit": "GB",       "unit_quantity": 10},
    {"slug": "extra-api-10k",    "name": "Extra API Calls (10,000)",    "type": "extra_api_calls", "price_usd": Decimal("5.00"),  "unit": "calls",    "unit_quantity": 10000},
    {"slug": "extra-qr-500",     "name": "Extra QR Codes (500)",        "type": "extra_qr",        "price_usd": Decimal("5.00"),  "unit": "QR codes", "unit_quantity": 500},
    {"slug": "whatsapp-biz",     "name": "WhatsApp Business API",       "type": "whatsapp_business","price_usd": Decimal("25.00"), "unit": "month",    "unit_quantity": 1},
    {"slug": "custom-ai",        "name": "Custom AI Model",             "type": "custom_ai",       "price_usd": Decimal("199.00"),"unit": "month",    "unit_quantity": 1},
    {"slug": "dedicated-kafka",  "name": "Dedicated Kafka Cluster",     "type": "dedicated_kafka", "price_usd": Decimal("99.00"), "unit": "month",    "unit_quantity": 1},
    {"slug": "advanced-trans",   "name": "Advanced Translation",        "type": "advanced_translation","price_usd": Decimal("15.00"),"unit": "month",  "unit_quantity": 1},
]


async def seed_plans_and_addons(db: AsyncSession) -> None:
    # Seed plans
    for plan_data in PLANS:
        existing = (await db.execute(select(Plan).where(Plan.slug == plan_data["slug"]))).scalar_one_or_none()
        if not existing:
            db.add(Plan(**plan_data))
            log.info("subscription.seed.plan_created", slug=plan_data["slug"])

    # Seed add-ons
    for addon_data in ADDONS:
        existing = (await db.execute(select(AddOn).where(AddOn.slug == addon_data["slug"]))).scalar_one_or_none()
        if not existing:
            db.add(AddOn(**addon_data))
            log.info("subscription.seed.addon_created", slug=addon_data["slug"])

    await db.commit()
    log.info("subscription.seed.complete")
