#!/bin/bash
# =============================================================================
# Riviwa Infra VM Startup Script
# Installs Docker, NVIDIA drivers, pulls configs, and starts:
#   - Kafka (4 KRaft brokers)
#   - Qdrant (vector DB)
#   - Ollama (LLM with T4 GPU)
#   - Translation service (NLLB-200, CPU)
#   - Spark (master + worker + jobs)
# =============================================================================
set -euo pipefail

log() { echo "[$(date '+%H:%M:%S')] $*" | tee -a /var/log/riviwa-startup.log; }

log "Starting Riviwa infra VM setup..."

# ── System updates ────────────────────────────────────────────────────────────
apt-get update -qq
apt-get install -y -qq curl wget git ca-certificates gnupg lsb-release

# ── Docker ────────────────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | bash
  usermod -aG docker $USER
  systemctl enable docker
  systemctl start docker
fi

# Docker Compose v2
if ! docker compose version &>/dev/null; then
  log "Installing Docker Compose..."
  COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
  curl -SL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-x86_64" \
    -o /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
  ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
fi

# ── NVIDIA drivers + container toolkit (for Ollama GPU) ──────────────────────
if ! command -v nvidia-smi &>/dev/null; then
  log "Installing NVIDIA drivers..."
  apt-get install -y -qq linux-headers-$(uname -r)
  # GCP Debian 12 NVIDIA driver
  curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/cuda-keyring_1.1-1_all.deb \
    -o /tmp/cuda-keyring.deb
  dpkg -i /tmp/cuda-keyring.deb
  apt-get update -qq
  apt-get install -y -qq cuda-drivers
  # NVIDIA Container Toolkit
  curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor \
    -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  apt-get update -qq
  apt-get install -y -qq nvidia-container-toolkit
  nvidia-ctk runtime configure --runtime=docker
  systemctl restart docker
  log "NVIDIA drivers installed"
fi

# ── Copy infra Docker Compose from GCS (or GitHub) ───────────────────────────
mkdir -p /opt/riviwa-infra
COMPOSE_DEST="/opt/riviwa-infra/docker-compose.yml"

# Try GCS first, fall back to GitHub
if ! gsutil cp gs://riviwa-staff/infra/docker-compose.yml "$COMPOSE_DEST" 2>/dev/null; then
  log "Pulling docker-compose from GitHub..."
  curl -fsSL "https://raw.githubusercontent.com/josako53/RiviwaGlobe/main/gcp/infra-vm/docker-compose.yml" \
    -o "$COMPOSE_DEST"
fi

# ── Write environment file for infra services ─────────────────────────────────
# These values are resolved at VM startup via GCP metadata / Secret Manager
VM_IP=$(curl -s -H "Metadata-Flavor: Google" \
  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip)

# Fetch secrets from Secret Manager
get_secret() {
  gcloud secrets versions access latest --secret="riviwa-${1}" 2>/dev/null || echo "CHANGE_ME"
}

PROJECT_ID=$(curl -s -H "Metadata-Flavor: Google" \
  http://metadata.google.internal/computeMetadata/v1/project/project-id)

cat > /opt/riviwa-infra/.env << EOF
# Auto-generated by startup.sh — do not edit manually
VM_IP=${VM_IP}
PROJECT_ID=${PROJECT_ID}

# Kafka advertised listeners (external = VPC IP, internal = docker net)
KAFKA_EXTERNAL_IP=${VM_IP}

# Translation service DB (Cloud SQL)
TRANSLATION_DATABASE_URL=$(get_secret TRANSLATION_DATABASE_URL)

# Redis (Memorystore)
REDIS_URL=$(get_secret REDIS_URL)

# Kafka bootstrap for translation service (self-referencing)
KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092,kafka-4:9092

# Internal service key
INTERNAL_SERVICE_KEY=$(get_secret INTERNAL_SERVICE_KEY)

# MinIO/GCS
MINIO_ENDPOINT=$(get_secret MINIO_ENDPOINT)
MINIO_ACCESS_KEY=$(get_secret MINIO_ACCESS_KEY)
MINIO_SECRET_KEY=$(get_secret MINIO_SECRET_KEY)

# Translation config
NLLB_ENABLED=true
NLLB_MODEL_NAME=facebook/nllb-200-distilled-1.3B
NLLB_DEVICE=cpu
TRANSLATION_PROVIDER=nllb
DEFAULT_LANGUAGE=sw
FALLBACK_LANGUAGE=en
ENVIRONMENT=production
APP_V1_STR=/api/v1
EOF

chmod 600 /opt/riviwa-infra/.env
log "Environment file written"

# ── Persistent data directories ───────────────────────────────────────────────
mkdir -p \
  /data/kafka-1 /data/kafka-2 /data/kafka-3 /data/kafka-4 \
  /data/qdrant /data/ollama /data/spark

# ── Start all infra services ──────────────────────────────────────────────────
cd /opt/riviwa-infra
log "Pulling Docker images..."
docker compose pull --quiet 2>/dev/null || true

log "Starting infra services..."
docker compose up -d

# Pull Ollama model after container starts
log "Pulling Ollama model (llama3.2:3b)..."
sleep 30  # wait for Ollama to be ready
docker exec reviwa-ollama ollama pull llama3.2:3b || \
  log "WARNING: Ollama model pull failed — retry manually: docker exec reviwa-ollama ollama pull llama3.2:3b"

log "All infra services started. VM is ready."
docker compose ps
