"""Add org operating hours, leadership roles, geo boundaries

Revision ID: 3c4e2b9e243a
Revises: 1f7ed83bfa25
Create Date: 2026-06-24 11:29:37.229846+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c4e2b9e243a'
down_revision: Union[str, None] = '1f7ed83bfa25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_geo_boundaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('boundary_type', sa.Enum('SERVICE_AREA', 'JURISDICTION', 'DELIVERY_ZONE', 'CATCHMENT', 'MONITORING', 'OPERATIONAL', name='geo_boundary_type'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bbox_min_lat', sa.Float(), nullable=True),
    sa.Column('bbox_max_lat', sa.Float(), nullable=True),
    sa.Column('bbox_min_lng', sa.Float(), nullable=True),
    sa.Column('bbox_max_lng', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['org_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_geo_boundaries_boundary_type'), 'org_geo_boundaries', ['boundary_type'], unique=False)
    op.create_index(op.f('ix_org_geo_boundaries_branch_id'), 'org_geo_boundaries', ['branch_id'], unique=False)
    op.create_index(op.f('ix_org_geo_boundaries_org_id'), 'org_geo_boundaries', ['org_id'], unique=False)
    op.create_table('org_leadership_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('role_title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('scope', sa.Enum('EXECUTIVE', 'MANAGEMENT', 'INCHARGE', 'FOCAL_PERSON', 'SPOKESPERSON', 'TECHNICAL', 'BOARD', name='leadership_scope'), nullable=False),
    sa.Column('duties', sa.Text(), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('parent_role_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['org_branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_role_id'], ['org_leadership_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_leadership_roles_branch_id'), 'org_leadership_roles', ['branch_id'], unique=False)
    op.create_index(op.f('ix_org_leadership_roles_org_id'), 'org_leadership_roles', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_leadership_roles_scope'), 'org_leadership_roles', ['scope'], unique=False)
    op.create_index(op.f('ix_org_leadership_roles_user_id'), 'org_leadership_roles', ['user_id'], unique=False)
    op.create_table('org_operating_hours',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='day_of_week'), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['org_branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'branch_id', 'day_of_week', name='uq_org_hours_scope_day')
    )
    op.create_index(op.f('ix_org_operating_hours_branch_id'), 'org_operating_hours', ['branch_id'], unique=False)
    op.create_index(op.f('ix_org_operating_hours_day_of_week'), 'org_operating_hours', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_org_operating_hours_org_id'), 'org_operating_hours', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_operating_hours_org_id'), table_name='org_operating_hours')
    op.drop_index(op.f('ix_org_operating_hours_day_of_week'), table_name='org_operating_hours')
    op.drop_index(op.f('ix_org_operating_hours_branch_id'), table_name='org_operating_hours')
    op.drop_table('org_operating_hours')
    op.drop_index(op.f('ix_org_leadership_roles_user_id'), table_name='org_leadership_roles')
    op.drop_index(op.f('ix_org_leadership_roles_scope'), table_name='org_leadership_roles')
    op.drop_index(op.f('ix_org_leadership_roles_org_id'), table_name='org_leadership_roles')
    op.drop_index(op.f('ix_org_leadership_roles_branch_id'), table_name='org_leadership_roles')
    op.drop_table('org_leadership_roles')
    op.drop_index(op.f('ix_org_geo_boundaries_org_id'), table_name='org_geo_boundaries')
    op.drop_index(op.f('ix_org_geo_boundaries_branch_id'), table_name='org_geo_boundaries')
    op.drop_index(op.f('ix_org_geo_boundaries_boundary_type'), table_name='org_geo_boundaries')
    op.drop_table('org_geo_boundaries')
    # ### end Alembic commands ###
