"""Add functionalities to org_content

Revision ID: 5b1ce6f16a16
Revises: 3c4e2b9e243a
Create Date: 2026-06-24 12:12:08.481741+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1ce6f16a16'
down_revision: Union[str, None] = '3c4e2b9e243a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_content', sa.Column('functionalities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_content', 'functionalities')
    # ### end Alembic commands ###
