"""add_orglocation_geocoding_fields

Revision ID: 1f7ed83bfa25
Revises: d1e2f3a4b5c6
Create Date: 2026-06-24 09:09:14.949764+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f7ed83bfa25'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('industries', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('industries', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('ix_industries_is_active'), table_name='industries')
    op.drop_index(op.f('ix_industries_slug'), table_name='industries')
    op.create_index(op.f('ix_industries_parent_id'), 'industries', ['parent_id'], unique=False)
    op.alter_column('industry_field_templates', 'field_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('industry_field_templates', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('industry_field_templates', 'is_visible_to_consumer',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('industry_field_templates', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('org_custom_field_defs', 'field_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('org_custom_field_defs', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('org_custom_field_defs', 'is_visible_to_consumer',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('org_custom_field_defs', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('org_custom_field_defs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('ix_org_custom_field_defs_entity_type'), table_name='org_custom_field_defs')
    op.add_column('org_locations', sa.Column('suburb', sa.String(length=150), nullable=True))
    op.add_column('org_locations', sa.Column('source', sa.String(length=10), server_default=sa.text("'manual'"), nullable=False))
    op.add_column('org_locations', sa.Column('display_name', sa.Text(), nullable=True))
    op.add_column('org_locations', sa.Column('address_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('org_locations', sa.Column('osm_id', sa.BigInteger(), nullable=True))
    op.add_column('org_locations', sa.Column('osm_type', sa.String(length=10), nullable=True))
    op.add_column('org_locations', sa.Column('place_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_org_locations_place_id'), 'org_locations', ['place_id'], unique=False)
    op.create_index(op.f('ix_org_locations_suburb'), 'org_locations', ['suburb'], unique=False)
    op.alter_column('organisation_industries', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation_industries', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.drop_index(op.f('ix_org_locations_suburb'), table_name='org_locations')
    op.drop_index(op.f('ix_org_locations_place_id'), table_name='org_locations')
    op.drop_column('org_locations', 'place_id')
    op.drop_column('org_locations', 'osm_type')
    op.drop_column('org_locations', 'osm_id')
    op.drop_column('org_locations', 'address_components')
    op.drop_column('org_locations', 'display_name')
    op.drop_column('org_locations', 'source')
    op.drop_column('org_locations', 'suburb')
    op.create_index(op.f('ix_org_custom_field_defs_entity_type'), 'org_custom_field_defs', ['entity_type'], unique=False)
    op.alter_column('org_custom_field_defs', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('org_custom_field_defs', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('org_custom_field_defs', 'is_visible_to_consumer',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('org_custom_field_defs', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('org_custom_field_defs', 'field_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'text'::character varying"),
               existing_nullable=False)
    op.alter_column('industry_field_templates', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('industry_field_templates', 'is_visible_to_consumer',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('industry_field_templates', 'is_required',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('industry_field_templates', 'field_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'text'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_industries_parent_id'), table_name='industries')
    op.create_index(op.f('ix_industries_slug'), 'industries', ['slug'], unique=False)
    op.create_index(op.f('ix_industries_is_active'), 'industries', ['is_active'], unique=False)
    op.alter_column('industries', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True)
    op.alter_column('industries', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    # ### end Alembic commands ###
